# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Webyard of Vitnira
tagline:          A cozy clearing in the wild web
description:      The part of the web where Vitnira rambles about various topics she finds neato
url:              https://vitnira.github.io/digital-nemeton/
baseurl:          "/digital-nemeton/"

author:
  name:           Vitnira

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Vitnira/digital-nemeton
