# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Webyard of Vitnira
tagline:          A cozy clearing in the wild web
description:      The part of the web where Vitnira rambles about various topics she finds neato
url:              https://vitnira.github.io/digital-nemeton/
baseurl:          "/digital-nemeton/"

author:
  name:           Vitnira

paginate:         5

# Custom vars
version:          0.0.5

github:
  repo:           https://github.com/Vitnira/digital-nemeton

plugins:
  - jekyll-paginate
  - jekyll-gist

include:
  - assets/fonts