# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Webyard of Vitnira
tagline:          A cozy clearing in the wild web
description:      Vitnira's cozy clearing in the wyrd wild web
url:              https://vitnira.github.io/
baseurl:          "/digital-nemeton"

author:
  name:           Vitnira

paginate:         5


# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/Vitnira/digital-nemeton

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

include:
  - assets/fonts